import type { Locale } from "./locale";
import { messages } from "./messages";
import type {
  ActivityTemplate,
  LegalBasis,
  SystemTemplate,
  Tom,
  TransferMechanism,
  HostingRegion,
  DataSensitivity,
  EmployeeBand,
} from "./types";

export const EMPLOYEE_BANDS: { value: EmployeeBand; label: string; hint: string }[] = [
  { value: "1-9", label: "1–9", hint: "Solo or small team" },
  { value: "10-49", label: "10–49", hint: "Typical SME" },
  { value: "50-249", label: "50–249", hint: "Larger SME" },
  { value: "250+", label: "250+", hint: "A DPO is often required" },
];

export const INDUSTRIES = [
  "Professional services",
  "IT / software",
  "Retail / e-commerce",
  "Construction / trades",
  "Healthcare / clinic",
  "Hospitality",
  "Education / training",
  "Manufacturing",
  "Creative / agency",
  "Other",
];

export const DATA_TYPE_OPTIONS = [
  "Names",
  "Email addresses",
  "Phone numbers",
  "Home / work address",
  "CVR / company details",
  "Job title",
  "CV and application documents",
  "Employment contract",
  "Salary and bank details",
  "CPR / national ID",
  "Sick leave / health notes",
  "Performance reviews",
  "Invoices and payment data",
  "Order history",
  "Support tickets",
  "Website usage / cookies",
  "IP address",
  "Photos",
  "Login credentials",
];

export const DATA_SUBJECT_OPTIONS = [
  "Employees",
  "Job applicants",
  "Customers (B2B contacts)",
  "Consumers (B2C)",
  "Suppliers",
  "Website visitors",
  "Newsletter subscribers",
  "Shareholders / owners",
];

export const LEGAL_BASIS_OPTIONS: {
  value: LegalBasis;
  label: string;
  hint: string;
}[] = [
  {
    value: "contract",
    label: "Contract",
    hint: "Needed to deliver a service or employment contract",
  },
  {
    value: "legal_obligation",
    label: "Legal obligation",
    hint: "The law requires it (bookkeeping, tax, payroll)",
  },
  {
    value: "legitimate_interest",
    label: "Legitimate interest",
    hint: "A reasonable business need, balanced against people’s rights",
  },
  {
    value: "consent",
    label: "Consent",
    hint: "The person said yes, and can say no later",
  },
  {
    value: "vital_interest",
    label: "Vital interest",
    hint: "To protect someone’s life or safety — rare for SMEs",
  },
  {
    value: "public_task",
    label: "Public task",
    hint: "Usually for public authorities, not private companies",
  },
];

export const TRANSFER_OPTIONS: {
  value: TransferMechanism;
  label: string;
  hint: string;
}[] = [
  { value: "none", label: "No transfer outside the EU/EEA", hint: "Data stays in Europe" },
  { value: "adequacy", label: "Adequacy decision", hint: "Country is approved by the EU (e.g. UK, Japan)" },
  { value: "dpf", label: "EU–US Data Privacy Framework", hint: "US vendor is DPF-certified" },
  { value: "sccs", label: "Standard Contractual Clauses (SCCs)", hint: "The usual contract add-on with US/global vendors" },
  { value: "bcrs", label: "Binding Corporate Rules", hint: "Internal group rules — uncommon for SMEs" },
  { value: "derogation", label: "Specific exception", hint: "Only in narrow cases, e.g. explicit consent" },
];

export const REGION_OPTIONS: { value: HostingRegion; label: string }[] = [
  { value: "eu", label: "EU" },
  { value: "eea", label: "EEA" },
  { value: "uk", label: "United Kingdom" },
  { value: "us", label: "United States" },
  { value: "mixed", label: "Mixed / global" },
  { value: "unknown", label: "Not sure yet" },
];

export const SENSITIVITY_OPTIONS: {
  value: DataSensitivity;
  label: string;
  hint: string;
}[] = [
  { value: "standard", label: "Everyday data", hint: "Names, emails, invoices, job titles" },
  {
    value: "special",
    label: "Sensitive data (Art. 9)",
    hint: "Health, union membership, religion, biometrics",
  },
  {
    value: "criminal",
    label: "Criminal records (Art. 10)",
    hint: "Only if you actually check criminal records",
  },
];

export const SYSTEM_TEMPLATES: SystemTemplate[] = [
  {
    id: "m365",
    name: "Microsoft 365",
    vendor: "Microsoft",
    category: "Email & documents",
    purpose: "Email, files, calendars, and internal collaboration",
    dataTypes: ["Names", "Email addresses", "Calendar data", "Documents that may contain personal data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "eu",
    hostingNotes: "Use an EU tenant where possible. Some Microsoft cloud services may still involve US processing.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["it-admin", "support"],
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    vendor: "Google",
    category: "Email & documents",
    purpose: "Email, Drive, Calendar, and Docs",
    dataTypes: ["Names", "Email addresses", "Calendar data", "Documents that may contain personal data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "eu",
    hostingNotes: "Select EU data regions where available. Google may process some support/security data in the US.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["it-admin", "support"],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    vendor: "Dropbox",
    category: "Email & documents",
    purpose: "File storage and sharing",
    dataTypes: ["Names", "Email addresses", "Documents that may contain personal data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "us",
    hostingNotes: "Typically US-hosted. Confirm DPF / SCCs in the DPA. Prefer EU file locations where available.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["it-admin"],
  },
  {
    id: "nextcloud",
    name: "Nextcloud",
    vendor: "Self-hosted or host",
    category: "Email & documents",
    purpose: "Self-hosted files, calendar, and collaboration",
    dataTypes: ["Names", "Email addresses", "Calendar data", "Documents that may contain personal data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "eu",
    hostingNotes: "Depends on where you host it. Prefer an EU server you control.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["it-admin", "support"],
  },
  {
    id: "zoho-workplace",
    name: "Zoho Workplace",
    vendor: "Zoho",
    category: "Email & documents",
    purpose: "Email, documents, and internal collaboration",
    dataTypes: ["Names", "Email addresses", "Calendar data", "Documents that may contain personal data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "eu",
    hostingNotes: "Zoho offers EU data centres. Confirm the chosen region in the admin settings.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["it-admin", "support"],
  },
  {
    id: "spreadsheets",
    name: "Excel / Google Sheets",
    vendor: "Microsoft or Google",
    category: "Email & documents",
    purpose: "Spreadsheets that may hold customer, employee, or supplier data",
    dataTypes: ["Names", "Email addresses", "Phone numbers", "Invoices and payment data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "unknown",
    hostingNotes:
      "Local Excel files are not a cloud processor. Sheets in Google Drive or OneDrive follow that vendor’s hosting and DPA.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["accounting", "hr-payroll", "sales"],
  },
  {
    id: "economic",
    name: "e-conomic",
    vendor: "Visma",
    category: "Accounting",
    purpose: "Bookkeeping, invoicing, and financial reporting",
    dataTypes: ["Names", "Email addresses", "CVR / company details", "Invoices and payment data"],
    dataSubjects: ["Customers (B2B contacts)", "Suppliers", "Employees"],
    hostingRegion: "eu",
    hostingNotes: "Hosted in the EU (Denmark / Visma).",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["accounting"],
  },
  {
    id: "dinero",
    name: "Dinero",
    vendor: "Visma",
    category: "Accounting",
    purpose: "Bookkeeping and invoicing for smaller companies",
    dataTypes: ["Names", "Email addresses", "CVR / company details", "Invoices and payment data"],
    dataSubjects: ["Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "eu",
    hostingNotes: "Hosted in the EU.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["accounting"],
  },
  {
    id: "billy",
    name: "Billy",
    vendor: "Billy / Visma",
    category: "Accounting",
    purpose: "Invoicing and bookkeeping",
    dataTypes: ["Names", "Email addresses", "Invoices and payment data"],
    dataSubjects: ["Customers (B2B contacts)", "Suppliers"],
    hostingRegion: "eu",
    hostingNotes: "Hosted in the EU.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["accounting"],
  },
  {
    id: "business-central",
    name: "Business Central / Navision",
    vendor: "Microsoft",
    category: "Accounting",
    purpose: "ERP, bookkeeping, inventory, and invoicing",
    dataTypes: ["Names", "Email addresses", "CVR / company details", "Invoices and payment data", "Order history"],
    dataSubjects: ["Customers (B2B contacts)", "Suppliers", "Employees"],
    hostingRegion: "eu",
    hostingNotes: "Cloud BC can use EU data centres. Confirm region. On-premises stays where you host it.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["accounting", "sales"],
  },
  {
    id: "uniconta",
    name: "Uniconta",
    vendor: "Uniconta",
    category: "Accounting",
    purpose: "Danish ERP for bookkeeping, inventory, and invoicing",
    dataTypes: ["Names", "Email addresses", "CVR / company details", "Invoices and payment data", "Order history"],
    dataSubjects: ["Customers (B2B contacts)", "Suppliers", "Employees"],
    hostingRegion: "eu",
    hostingNotes: "Danish ERP, typically hosted in the EU.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["accounting", "sales"],
  },
  {
    id: "danlon",
    name: "Danløn",
    vendor: "Danløn",
    category: "Payroll",
    purpose: "Salary payments, holiday, and tax reporting",
    dataTypes: ["Names", "CPR / national ID", "Salary and bank details", "Employment contract"],
    dataSubjects: ["Employees"],
    hostingRegion: "eu",
    hostingNotes: "Danish payroll provider, EU hosted.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["hr-payroll"],
  },
  {
    id: "visma-payroll",
    name: "Visma Payroll / Løn",
    vendor: "Visma",
    category: "Payroll",
    purpose: "Payroll, tax, and employee master data",
    dataTypes: ["Names", "CPR / national ID", "Salary and bank details", "Employment contract"],
    dataSubjects: ["Employees"],
    hostingRegion: "eu",
    hostingNotes: "EU hosted.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["hr-payroll"],
  },
  {
    id: "zenegy",
    name: "Zenegy",
    vendor: "Zenegy",
    category: "Payroll",
    purpose: "Payroll, HR, and employee master data",
    dataTypes: ["Names", "CPR / national ID", "Salary and bank details", "Employment contract", "Sick leave / health notes"],
    dataSubjects: ["Employees"],
    hostingRegion: "eu",
    hostingNotes: "Danish payroll / HR suite, typically EU hosted.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["hr-payroll"],
  },
  {
    id: "datalon",
    name: "DataLøn",
    vendor: "Visma / DataLøn",
    category: "Payroll",
    purpose: "Salary payments, holiday, and tax reporting",
    dataTypes: ["Names", "CPR / national ID", "Salary and bank details", "Employment contract"],
    dataSubjects: ["Employees"],
    hostingRegion: "eu",
    hostingNotes: "Danish payroll provider, EU hosted.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["hr-payroll"],
  },
  {
    id: "salary",
    name: "Salary",
    vendor: "Salary",
    category: "Payroll",
    purpose: "Payroll and employee administration for smaller companies",
    dataTypes: ["Names", "CPR / national ID", "Salary and bank details", "Employment contract"],
    dataSubjects: ["Employees"],
    hostingRegion: "eu",
    hostingNotes: "Danish payroll tool, typically EU hosted.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["hr-payroll"],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    vendor: "HubSpot",
    category: "CRM",
    purpose: "Sales pipeline, customer contacts, and marketing",
    dataTypes: ["Names", "Email addresses", "Phone numbers", "Job title", "Order history"],
    dataSubjects: ["Customers (B2B contacts)", "Newsletter subscribers"],
    hostingRegion: "us",
    hostingNotes: "Primarily US-hosted. Confirm DPF certification and SCCs in your DPA.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["sales", "marketing"],
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    vendor: "Pipedrive",
    category: "CRM",
    purpose: "Sales pipeline and customer contacts",
    dataTypes: ["Names", "Email addresses", "Phone numbers", "Job title"],
    dataSubjects: ["Customers (B2B contacts)"],
    hostingRegion: "eu",
    hostingNotes: "EU hosting available. Confirm your chosen region in the admin settings.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["sales"],
  },
  {
    id: "salesforce",
    name: "Salesforce",
    vendor: "Salesforce",
    category: "CRM",
    purpose: "Sales pipeline, customer contacts, and service",
    dataTypes: ["Names", "Email addresses", "Phone numbers", "Job title", "Order history"],
    dataSubjects: ["Customers (B2B contacts)"],
    hostingRegion: "mixed",
    hostingNotes: "Confirm your Salesforce instance region. Hyperforce EU is available; some support data may leave the EEA.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "sccs",
    suggestedActivityIds: ["sales", "support"],
  },
  {
    id: "superoffice",
    name: "SuperOffice",
    vendor: "SuperOffice",
    category: "CRM",
    purpose: "Nordic CRM for sales and customer follow-up",
    dataTypes: ["Names", "Email addresses", "Phone numbers", "Job title"],
    dataSubjects: ["Customers (B2B contacts)"],
    hostingRegion: "eu",
    hostingNotes: "Nordic vendor. Confirm EU hosting in your agreement.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["sales"],
  },
  {
    id: "shopify",
    name: "Shopify",
    vendor: "Shopify",
    category: "E-commerce",
    purpose: "Online store, orders, and customer accounts",
    dataTypes: ["Names", "Email addresses", "Home / work address", "Order history", "Invoices and payment data"],
    dataSubjects: ["Consumers (B2C)", "Customers (B2B contacts)"],
    hostingRegion: "mixed",
    hostingNotes: "Shopify offers EU stores; some subprocessors may be outside the EEA.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "sccs",
    suggestedActivityIds: ["sales", "support"],
  },
  {
    id: "wordpress",
    name: "Website (WordPress)",
    vendor: "Self-hosted or host",
    category: "Website",
    purpose: "Company website, contact forms, and content",
    dataTypes: ["Names", "Email addresses", "Website usage / cookies", "IP address"],
    dataSubjects: ["Website visitors", "Customers (B2B contacts)"],
    hostingRegion: "eu",
    hostingNotes: "Depends on your web host. Prefer an EU host.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["website", "marketing"],
  },
  {
    id: "cookiebot",
    name: "Cookiebot",
    vendor: "Usercentrics",
    category: "Website",
    purpose: "Cookie consent and scanning",
    dataTypes: ["Website usage / cookies", "IP address"],
    dataSubjects: ["Website visitors"],
    hostingRegion: "eu",
    hostingNotes: "EU hosted consent records.",
    isProcessor: true,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["website"],
  },
  {
    id: "ga4",
    name: "Google Analytics 4",
    vendor: "Google",
    category: "Analytics",
    purpose: "Website statistics",
    dataTypes: ["Website usage / cookies", "IP address"],
    dataSubjects: ["Website visitors"],
    hostingRegion: "us",
    hostingNotes: "US processing is typical. Use consent mode and a DPA. Many SMEs switch to EU analytics instead.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["website"],
  },
  {
    id: "meta-ads",
    name: "Meta Ads / Pixel",
    vendor: "Meta",
    category: "Marketing",
    purpose: "Advertising and conversion tracking",
    dataTypes: ["Website usage / cookies", "Email addresses"],
    dataSubjects: ["Website visitors", "Newsletter subscribers", "Consumers (B2C)"],
    hostingRegion: "us",
    hostingNotes: "US vendor. Ads should run on consent for tracking.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["marketing"],
  },
  {
    id: "mailchimp",
    name: "Mailchimp / Intuit",
    vendor: "Intuit",
    category: "Marketing",
    purpose: "Newsletters and email campaigns",
    dataTypes: ["Names", "Email addresses"],
    dataSubjects: ["Newsletter subscribers", "Customers (B2B contacts)"],
    hostingRegion: "us",
    hostingNotes: "US hosted. Require consent or a documented legitimate-interest assessment for B2B.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["marketing"],
  },
  {
    id: "zendesk",
    name: "Zendesk",
    vendor: "Zendesk",
    category: "Support",
    purpose: "Customer support tickets",
    dataTypes: ["Names", "Email addresses", "Support tickets"],
    dataSubjects: ["Customers (B2B contacts)", "Consumers (B2C)"],
    hostingRegion: "eu",
    hostingNotes: "Choose EU data centre in Zendesk settings.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "sccs",
    suggestedActivityIds: ["support"],
  },
  {
    id: "intercom",
    name: "Intercom",
    vendor: "Intercom",
    category: "Support",
    purpose: "Chat support and customer messaging",
    dataTypes: ["Names", "Email addresses", "Support tickets"],
    dataSubjects: ["Customers (B2B contacts)", "Website visitors"],
    hostingRegion: "us",
    hostingNotes: "Typically US-hosted. Confirm SCCs / DPF in the DPA.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["support"],
  },
  {
    id: "slack",
    name: "Slack",
    vendor: "Salesforce",
    category: "Collaboration",
    purpose: "Internal chat. May contain customer names in messages.",
    dataTypes: ["Names", "Email addresses", "Support tickets"],
    dataSubjects: ["Employees", "Customers (B2B contacts)"],
    hostingRegion: "eu",
    hostingNotes: "Select the EU Slack workspace region if available.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["it-admin"],
  },
  {
    id: "linkedin",
    name: "LinkedIn Recruiter / Jobs",
    vendor: "Microsoft / LinkedIn",
    category: "Recruitment",
    purpose: "Sourcing and contacting candidates",
    dataTypes: ["Names", "Email addresses", "CV and application documents", "Job title"],
    dataSubjects: ["Job applicants"],
    hostingRegion: "us",
    hostingNotes: "US / global processing. Keep unsuccessful applications no longer than needed.",
    isProcessor: true,
    transfersOutsideEea: true,
    transferMechanism: "dpf",
    suggestedActivityIds: ["recruitment"],
  },
  {
    id: "banking",
    name: "Business bank",
    vendor: "Your bank",
    category: "Finance",
    purpose: "Payments, salary transfers, and account administration",
    dataTypes: ["Names", "Salary and bank details", "Invoices and payment data"],
    dataSubjects: ["Employees", "Suppliers", "Customers (B2B contacts)"],
    hostingRegion: "eu",
    hostingNotes: "Danish / EU banks typically keep data in the EEA. The bank is usually an independent controller, not your processor.",
    isProcessor: false,
    transfersOutsideEea: false,
    transferMechanism: "none",
    suggestedActivityIds: ["accounting", "hr-payroll"],
  },
];

export const SYSTEM_CATEGORY_DEFAULTS: Record<
  string,
  {
    purpose: string;
    dataTypes: string[];
    dataSubjects: string[];
    suggestedActivityIds: string[];
  }
> = {
  "Email & documents": {
    purpose: "Email, files, and internal collaboration",
    dataTypes: ["Names", "Email addresses", "Documents that may contain personal data"],
    dataSubjects: ["Employees", "Customers (B2B contacts)", "Suppliers"],
    suggestedActivityIds: ["it-admin", "support"],
  },
  Accounting: {
    purpose: "Bookkeeping, invoicing, and financial reporting",
    dataTypes: ["Names", "Email addresses", "CVR / company details", "Invoices and payment data"],
    dataSubjects: ["Customers (B2B contacts)", "Suppliers", "Employees"],
    suggestedActivityIds: ["accounting"],
  },
  Payroll: {
    purpose: "Salary payments, holiday, and tax reporting",
    dataTypes: ["Names", "CPR / national ID", "Salary and bank details", "Employment contract"],
    dataSubjects: ["Employees"],
    suggestedActivityIds: ["hr-payroll"],
  },
  CRM: {
    purpose: "Sales pipeline and customer contacts",
    dataTypes: ["Names", "Email addresses", "Phone numbers", "Job title"],
    dataSubjects: ["Customers (B2B contacts)"],
    suggestedActivityIds: ["sales"],
  },
  "E-commerce": {
    purpose: "Online store, orders, and customer accounts",
    dataTypes: ["Names", "Email addresses", "Home / work address", "Order history", "Invoices and payment data"],
    dataSubjects: ["Consumers (B2C)", "Customers (B2B contacts)"],
    suggestedActivityIds: ["sales", "support"],
  },
  Website: {
    purpose: "Company website, contact forms, and content",
    dataTypes: ["Names", "Email addresses", "Website usage / cookies", "IP address"],
    dataSubjects: ["Website visitors", "Customers (B2B contacts)"],
    suggestedActivityIds: ["website", "marketing"],
  },
  Analytics: {
    purpose: "Website statistics",
    dataTypes: ["Website usage / cookies", "IP address"],
    dataSubjects: ["Website visitors"],
    suggestedActivityIds: ["website"],
  },
  Marketing: {
    purpose: "Newsletters, campaigns, or advertising",
    dataTypes: ["Names", "Email addresses"],
    dataSubjects: ["Newsletter subscribers", "Customers (B2B contacts)"],
    suggestedActivityIds: ["marketing"],
  },
  Support: {
    purpose: "Customer support tickets and messaging",
    dataTypes: ["Names", "Email addresses", "Support tickets"],
    dataSubjects: ["Customers (B2B contacts)", "Consumers (B2C)"],
    suggestedActivityIds: ["support"],
  },
  Collaboration: {
    purpose: "Internal chat and collaboration. May contain customer names.",
    dataTypes: ["Names", "Email addresses"],
    dataSubjects: ["Employees"],
    suggestedActivityIds: ["it-admin"],
  },
  Recruitment: {
    purpose: "Sourcing and contacting candidates",
    dataTypes: ["Names", "Email addresses", "CV and application documents", "Job title"],
    dataSubjects: ["Job applicants"],
    suggestedActivityIds: ["recruitment"],
  },
  Finance: {
    purpose: "Payments and account administration",
    dataTypes: ["Names", "Salary and bank details", "Invoices and payment data"],
    dataSubjects: ["Employees", "Suppliers", "Customers (B2B contacts)"],
    suggestedActivityIds: ["accounting"],
  },
  Other: {
    purpose: "",
    dataTypes: ["Names", "Email addresses"],
    dataSubjects: ["Employees"],
    suggestedActivityIds: ["it-admin"],
  },
};

export const ACTIVITY_TEMPLATES: ActivityTemplate[] = [
  {
    id: "hr-payroll",
    name: "HR & payroll",
    department: "People / Finance",
    purpose: "Employ staff, pay salary, report tax and holiday, and keep personnel files.",
    dataSubjects: ["Employees"],
    personalData: [
      "Names",
      "Address",
      "CPR / national ID",
      "Bank details",
      "Salary",
      "Tax information",
      "Employment contracts",
      "Next of kin (if collected)",
    ],
    sensitivity: ["standard", "special"],
    legalBases: ["contract", "legal_obligation"],
    legalBasisNotes:
      "Employment contract plus legal duties for tax, holiday, and bookkeeping. Sick-leave notes are health data — keep them minimal and well protected.",
    recipients: ["Payroll provider", "SKAT / tax authority", "Pension / insurance (if used)", "Accountant"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "Duration of employment + 5 years (Danish bookkeeping / tax rules). Delete residual HR files when no longer needed.",
  },
  {
    id: "recruitment",
    name: "Recruitment",
    department: "People",
    purpose: "Receive applications, assess candidates, and hire.",
    dataSubjects: ["Job applicants"],
    personalData: ["Names", "Email addresses", "Phone numbers", "CV", "Cover letter", "Interview notes"],
    sensitivity: ["standard"],
    legalBases: ["legitimate_interest", "consent"],
    legalBasisNotes:
      "Legitimate interest to fill a role. Ask consent if you want to keep a CV in a talent pool after the process ends.",
    recipients: ["Hiring managers", "Recruitment platform (if used)"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "Unsuccessful applicants: 6 months after the process ends, unless they agree to a longer talent-pool period.",
  },
  {
    id: "accounting",
    name: "Accounting & bookkeeping",
    department: "Finance",
    purpose: "Issue invoices, pay suppliers, and meet bookkeeping law.",
    dataSubjects: ["Customers (B2B contacts)", "Suppliers", "Employees"],
    personalData: ["Names", "Email addresses", "CVR", "Invoice lines", "Payment references"],
    sensitivity: ["standard"],
    legalBases: ["legal_obligation", "contract"],
    legalBasisNotes: "Danish Bookkeeping Act and tax rules require financial records to be kept.",
    recipients: ["Accountant / auditor", "Bank", "SKAT", "Accounting software provider"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "5 years from the end of the financial year (Danish Bookkeeping Act).",
  },
  {
    id: "sales",
    name: "B2B sales & customer management",
    department: "Sales",
    purpose: "Manage leads, quotes, contracts, and ongoing customer relationships.",
    dataSubjects: ["Customers (B2B contacts)"],
    personalData: ["Names", "Work email", "Phone", "Job title", "Company", "Meeting notes", "Contract data"],
    sensitivity: ["standard"],
    legalBases: ["contract", "legitimate_interest"],
    legalBasisNotes:
      "Contract for existing customers. Legitimate interest for relevant B2B prospecting — keep it proportionate and offer an easy opt-out.",
    recipients: ["CRM provider", "Email provider", "Delivery / implementation partners (if any)"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "Active relationship + 5 years for contracts and invoices. Sales notes: 2 years after last contact if no contract.",
  },
  {
    id: "support",
    name: "Customer support",
    department: "Support",
    purpose: "Answer questions, handle complaints, and keep service quality.",
    dataSubjects: ["Customers (B2B contacts)", "Consumers (B2C)"],
    personalData: ["Names", "Email addresses", "Ticket content", "Order references"],
    sensitivity: ["standard"],
    legalBases: ["contract", "legitimate_interest"],
    legalBasisNotes: "Needed to perform the customer contract and improve service.",
    recipients: ["Support platform", "Product / engineering staff"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "2 years after the ticket is closed, unless a longer period is needed for a dispute or legal claim.",
  },
  {
    id: "marketing",
    name: "Marketing & newsletters",
    department: "Marketing",
    purpose: "Send newsletters, run campaigns, and measure interest.",
    dataSubjects: ["Newsletter subscribers", "Customers (B2B contacts)", "Website visitors"],
    personalData: ["Names", "Email addresses", "Company", "Campaign engagement"],
    sensitivity: ["standard"],
    legalBases: ["consent", "legitimate_interest"],
    legalBasisNotes:
      "Consent for most email marketing. Existing B2B customers may be contacted about similar products with a clear unsubscribe.",
    recipients: ["Email platform", "Ads platforms (if used)"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "Until the person unsubscribes, then suppress the address. Proof of consent: 2 years after last use.",
  },
  {
    id: "website",
    name: "Website & cookies",
    department: "Marketing / IT",
    purpose: "Run the company website, contact forms, and (if used) statistics.",
    dataSubjects: ["Website visitors"],
    personalData: ["IP address", "Cookie identifiers", "Form submissions", "Device / browser data"],
    sensitivity: ["standard"],
    legalBases: ["consent", "legitimate_interest"],
    legalBasisNotes:
      "Necessary cookies can rely on legitimate interest / strict necessity. Statistics and marketing cookies need consent.",
    recipients: ["Web host", "Consent tool", "Analytics provider (if used)"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "Consent records: 12 months. Analytics identifiers: 14 months or less. Contact form messages: 12 months.",
  },
  {
    id: "it-admin",
    name: "IT administration & access",
    department: "IT",
    purpose: "Create user accounts, manage access, logs, and backups.",
    dataSubjects: ["Employees"],
    personalData: ["Names", "Work email", "Login credentials", "Access logs", "Device identifiers"],
    sensitivity: ["standard"],
    legalBases: ["contract", "legitimate_interest"],
    legalBasisNotes: "Needed to give staff tools and to protect the company against misuse.",
    recipients: ["Cloud / identity providers"],
    transfersOutsideEea: false,
    transferCountries: "",
    transferMechanism: "none",
    retention: "Account data: while employed + 30 days. Security logs: 6–12 months.",
  },
];

export const DEFAULT_TOMS: Omit<Tom, "enabled">[] = [
  {
    id: "mfa",
    label: "Multi-factor authentication (MFA)",
    description: "Turn on MFA for email, cloud admin, payroll, and accounting.",
  },
  {
    id: "encryption-transit",
    label: "Encryption in transit",
    description: "HTTPS / TLS for websites and cloud tools.",
  },
  {
    id: "encryption-rest",
    label: "Encryption at rest",
    description: "Rely on cloud providers’ disk encryption; encrypt laptops with FileVault / BitLocker.",
  },
  {
    id: "access-control",
    label: "Role-based access",
    description: "People only see the data they need. Admin rights are limited.",
  },
  {
    id: "offboarding",
    label: "Joiners / leavers process",
    description: "Create and remove accounts on the same day someone starts or leaves.",
  },
  {
    id: "backups",
    label: "Backups",
    description: "Daily backups of critical systems, with a restore test at least once a year.",
  },
  {
    id: "device-lock",
    label: "Locked devices",
    description: "Screen lock, strong passwords or passkeys, and automatic updates.",
  },
  {
    id: "dpas",
    label: "Data processing agreements",
    description: "A signed DPA with each vendor that processes personal data for you.",
  },
  {
    id: "confidentiality",
    label: "Staff confidentiality",
    description: "Employment contracts include a confidentiality clause. Short GDPR intro for new hires.",
  },
  {
    id: "incident",
    label: "Incident contact",
    description: "You know who to call if data is lost or leaked, and to notify the DPA within 72 hours if required.",
  },
  {
    id: "logging",
    label: "Access logging",
    description: "Admin actions and logins are logged in your main cloud tools.",
  },
  {
    id: "disposal",
    label: "Secure disposal",
    description: "Old laptops and USB drives are wiped or destroyed. Paper with personal data is shredded.",
  },
];

function resolveLocale(locale: unknown): Locale {
  return locale === "en" || locale === "da" ? locale : "da";
}

export function legalBasisLabel(value: LegalBasis, locale: Locale = "da"): string {
  return messages[resolveLocale(locale)].legalBasis[value]?.label ?? value;
}

export function transferLabel(value: TransferMechanism, locale: Locale = "da"): string {
  return messages[resolveLocale(locale)].transfers[value]?.label ?? value;
}

export function regionLabel(value: HostingRegion, locale: Locale = "da"): string {
  return messages[resolveLocale(locale)].regions[value] ?? value;
}

export function sensitivityLabel(value: DataSensitivity, locale: Locale = "da"): string {
  return messages[resolveLocale(locale)].sensitivity[value]?.label ?? value;
}
